export const actionTypes: {
  INIT_STRUCTURE: 'INIT_STRUCTURE',
  SET_ROOT_DIR_ID: 'SET_ROOT_DIR_ID',
  SET_STRUCTURE: 'SET_STRUCTURE',
  GET_STRUCTURE: 'GET_STRUCTURE',
  CHANGE_ITEM_DATA: 'CHANGE_ITEM',
} = {
  INIT_STRUCTURE: 'INIT_STRUCTURE',
  SET_ROOT_DIR_ID: 'SET_ROOT_DIR_ID',
  SET_STRUCTURE: 'SET_STRUCTURE',
  GET_STRUCTURE: 'GET_STRUCTURE',
  CHANGE_ITEM_DATA: 'CHANGE_ITEM',
}

